# Generated by Django 4.2.5 on 2023-09-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="corgi",
            name="corgies_per_click",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="corgi",
            name="corgies_per_second",
            field=models.IntegerField(default=0),
        ),
    ]
