# Generated by Django 4.2.5 on 2023-09-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_corgi_corgies_per_click_corgi_corgies_per_second"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corgi",
            name="corgies_per_click",
            field=models.IntegerField(default=1),
        ),
    ]
